var cardArr = [
  { top: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  right: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  bottom: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  left: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  img: 'url("./img/tiles/topCastle.png")'},

  { top: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  right: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  bottom: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  left: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  img: 'url("./img/tiles/rightCastle.png")'},

  { top: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  right: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  bottom: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  left: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  img: 'url("./img/tiles/rightLeftBotCastle.png")'},

  { top: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  right: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  bottom: { type: 'grass', occupied: false, occupant: '', pointValue: 0},
  left: { type: 'castle', occupied: false, occupant: '', pointValue: 1},
  img: 'url("./img/tiles/rightLeftCastle.png")'},

  { top: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  right: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  bottom: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  left: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  img: 'url("./img/tiles/rightBotCastle.png")'},

  { top: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  right: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  bottom: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  left: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  img: 'url("./img/tiles/leftBotCastle.png")'},

  { top: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  right: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  bottom: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  left: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  img: 'url("./img/tiles/leftCastle.png")'},

  { top: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  right: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  bottom: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  left: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  img: 'url("./img/tiles/topRightCastle.png")'},

  { top: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  right: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  bottom: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  left: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  img: 'url("./img/tiles/leftCastle.png")'},

  { top: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  right: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  bottom: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  left: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  img: 'url("./img/tiles/leftTopBotCastle.png")'},

  { top: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  right: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  bottom: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  left: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  img: 'url("./img/tiles/topCastle.png")'},

  { top: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  right: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  bottom: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  left: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  img: 'url("./img/tiles/leftTopBotCastle.png")'},

  { top: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  right: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  bottom: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  left: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  img: 'url("./img/tiles/botCastle.png")'},

  { top: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  right: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  bottom: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  left: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  img: 'url("./img/tiles/leftBotCastle.png")'},

  { top: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  right: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  bottom: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  left: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  img: 'url("./img/tiles/topBotCastle.png")'},

  { top: { type: 'castle', occupied: false, occupant: '', pointValue: 1}, 
  right: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  bottom: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  left: { type: 'grass', occupied: false, occupant: '', pointValue: 0}, 
  img: 'url("./img/tiles/topCastle.png")'},
]